import 'dart:async';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'pet_animation.dart';
import 'pet_controller.dart';
import 'pet_painter.dart';
import 'pet_state.dart';

/// The spritesheet's cells, in strip order. The first five are the design
/// sheet's pixel row; blink is derived from idle by the sheet tool so the
/// idle<->blink swap moves nothing but the eyes.
enum PixelFrame { idle, walk1, walk2, jump, wink, blink }

/// Frame images at the sheet's native 48x64, one per [PixelFrame].
///
/// Source of truth is `assets/pixel_cat_spritesheet.png` — a horizontal strip
/// of six 48x64 cells in [PixelFrame] order (288x64 total). Until that asset
/// ships, the frames are generated by rasterising the vector [PetPainter] at
/// 48x64 and snapping every pixel to the sheet's palette, which produces real
/// pixel art with hard edges from the same approved character.
class PixelCatSprites {
  const PixelCatSprites._();

  static const spriteSize = Size(48, 64);
  static const assetPath = 'assets/pixel_cat_spritesheet.png';

  static Future<Map<PixelFrame, ui.Image>>? _loading;

  static Future<Map<PixelFrame, ui.Image>> frames() => _loading ??= _load();

  static Future<Map<PixelFrame, ui.Image>> _load() async {
    try {
      final data = await rootBundle.load(assetPath);
      final codec = await ui.instantiateImageCodec(data.buffer.asUint8List());
      final sheet = (await codec.getNextFrame()).image;
      return _slice(sheet);
    } catch (_) {
      // No spritesheet in the bundle (yet): build placeholder pixels from
      // the vector cat.
      return _placeholder();
    }
  }

  static Future<Map<PixelFrame, ui.Image>> _slice(ui.Image sheet) async {
    final frames = <PixelFrame, ui.Image>{};
    for (final frame in PixelFrame.values) {
      final recorder = ui.PictureRecorder();
      final canvas = Canvas(recorder);
      canvas.drawImageRect(
        sheet,
        Rect.fromLTWH(
          frame.index * spriteSize.width,
          0,
          spriteSize.width,
          spriteSize.height,
        ),
        Rect.fromLTWH(0, 0, spriteSize.width, spriteSize.height),
        Paint()..filterQuality = FilterQuality.none,
      );
      frames[frame] = await recorder.endRecording().toImage(
        spriteSize.width.toInt(),
        spriteSize.height.toInt(),
      );
    }
    return frames;
  }

  /// The poses behind each placeholder cell. Jump is rendered WITHOUT its
  /// lift: the sprite is the airborne body only, and the widget supplies the
  /// hop as a translation, exactly as it will with the real spritesheet.
  static PetPose _poseFor(PixelFrame frame) => switch (frame) {
    PixelFrame.idle => PetChoreography.pose(PetState.idle, 0),
    PixelFrame.walk1 => PetChoreography.pose(PetState.walk, 0.25),
    PixelFrame.walk2 => PetChoreography.pose(PetState.walk, 0.75),
    PixelFrame.jump => _grounded(PetChoreography.pose(PetState.jump, 0.47)),
    PixelFrame.wink => PetChoreography.pose(PetState.wink, 0.45),
    PixelFrame.blink => const PetPose(leftEyeOpen: 0, rightEyeOpen: 0),
  };

  static PetPose _grounded(PetPose p) => PetPose(
    tilt: p.tilt,
    legTuck: p.legTuck,
    armRaise: p.armRaise,
    tailSway: p.tailSway,
    leftEyeOpen: p.leftEyeOpen,
    rightEyeOpen: p.rightEyeOpen,
    happy: p.happy,
  );

  /// The sheet's palette as (match, paint) pairs. Every rasterised pixel
  /// snaps to the entry whose match colour is nearest and takes its paint
  /// colour — which is what turns smooth vector output into honest pixels.
  ///
  /// The extra blend anchors matter: an anti-aliased edge between cream and
  /// the outline lands almost exactly on pink in RGB distance, and without
  /// an anchor claiming that midpoint for the outline, every limb grows a
  /// pink rim.
  static const _palette = <(Color, Color)>[
    (PetPainter.cream, PetPainter.cream),
    (PetPainter.outline, PetPainter.outline),
    (PetPainter.earPink, PetPainter.earPink),
    (PetPainter.ink, PetPainter.ink),
    (Color(0xFFFFFFFF), Color(0xFFFFFFFF)),
    // cream/outline blend -> outline; ink/cream blend -> outline (a soft
    // dark rim reads as line art, a black one reads as dirt).
    (Color(0xFFDFD6C5), PetPainter.outline),
    (Color(0xFF8B857B), PetPainter.outline),
  ];

  static Future<Map<PixelFrame, ui.Image>> _placeholder() async {
    final frames = <PixelFrame, ui.Image>{};
    for (final frame in PixelFrame.values) {
      final recorder = ui.PictureRecorder();
      final canvas = Canvas(recorder);
      PetPainter(
        pose: _poseFor(frame),
        showShadow: false,
      ).paint(canvas, spriteSize);
      final soft = await recorder.endRecording().toImage(
        spriteSize.width.toInt(),
        spriteSize.height.toInt(),
      );
      frames[frame] = await _quantise(soft);
    }
    return frames;
  }

  static Future<ui.Image> _quantise(ui.Image src) async {
    final data = (await src.toByteData(
      format: ui.ImageByteFormat.rawStraightRgba,
    ))!;
    final px = data.buffer.asUint8List();
    for (var i = 0; i < px.length; i += 4) {
      if (px[i + 3] < 112) {
        px[i] = px[i + 1] = px[i + 2] = px[i + 3] = 0;
        continue;
      }
      var best = _palette.first.$2;
      var bestDistance = 1 << 30;
      for (final (match, paint) in _palette) {
        final dr = px[i] - ((match.r * 255).round());
        final dg = px[i + 1] - ((match.g * 255).round());
        final db = px[i + 2] - ((match.b * 255).round());
        final distance = dr * dr + dg * dg + db * db;
        if (distance < bestDistance) {
          bestDistance = distance;
          best = paint;
        }
      }
      px[i] = (best.r * 255).round();
      px[i + 1] = (best.g * 255).round();
      px[i + 2] = (best.b * 255).round();
      px[i + 3] = 255;
    }
    final completer = Completer<ui.Image>();
    ui.decodeImageFromPixels(
      px,
      src.width,
      src.height,
      ui.PixelFormat.rgba8888,
      completer.complete,
    );
    return completer.future;
  }
}

/// Pure frame-sequencing rules, kept off the widget so they can be tested.
class PixelChoreography {
  const PixelChoreography._();

  /// The two stride poses, alternating directly. Passing through the full
  /// standing frame between steps (the spec's first idea) read as a stutter
  /// — step, attention, step — and at 150ms the whole thing blurred.
  static const walkCycle = [PixelFrame.walk1, PixelFrame.walk2];

  static const walkFrameInterval = Duration(milliseconds: 260);
  static const winkHold = Duration(milliseconds: 450);
  static const jumpDuration = Duration(milliseconds: 700);
  static const blinkHold = Duration(milliseconds: 150);

  /// Peak of the jump hop, in sprite pixels (pre-scale).
  static const jumpHopPx = 9.0;

  static PixelFrame walkFrameAt(int tick) => walkCycle[tick % walkCycle.length];

  /// A pause between idle blinks: settled, never metronomic.
  static Duration nextBlinkDelay(math.Random random) =>
      Duration(milliseconds: 2600 + random.nextInt(3000));
}

/// Plays the pixel cat: owns frame timing per [PetState], the jump hop, and
/// nothing else. Pointer handling and sizing live with the caller.
class PixelSpriteAnimation extends StatefulWidget {
  const PixelSpriteAnimation({
    super.key,
    required this.controller,
    required this.scale,
    this.onOneShotComplete,
  });

  final PetController controller;

  /// Integer magnification. 48x64 pixels are drawn as scale-sized squares —
  /// never fractional, or the grid shimmers.
  final int scale;

  /// Fired when a jump or wink finishes; the owner decides what plays next.
  final VoidCallback? onOneShotComplete;

  @override
  State<PixelSpriteAnimation> createState() => _PixelSpriteAnimationState();
}

class _PixelSpriteAnimationState extends State<PixelSpriteAnimation>
    with SingleTickerProviderStateMixin {
  Map<PixelFrame, ui.Image>? _frames;
  PixelFrame _frame = PixelFrame.idle;
  Timer? _timer;
  int _walkTick = 0;
  final _random = math.Random();
  int _playedGeneration = -1;

  late final AnimationController _hop = AnimationController(
    vsync: this,
    duration: PixelChoreography.jumpDuration,
  );

  @override
  void initState() {
    super.initState();
    PixelCatSprites.frames().then((frames) {
      if (!mounted) return;
      setState(() => _frames = frames);
    });
    widget.controller.addListener(_sync);
    _hop.addStatusListener(_onHopStatus);
    _play();
  }

  @override
  void didUpdateWidget(PixelSpriteAnimation oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.controller != widget.controller) {
      oldWidget.controller.removeListener(_sync);
      widget.controller.addListener(_sync);
      _play();
    }
  }

  @override
  void dispose() {
    widget.controller.removeListener(_sync);
    _timer?.cancel();
    _hop.dispose();
    super.dispose();
  }

  void _sync() {
    if (!mounted) return;
    if (widget.controller.generation != _playedGeneration) _play();
  }

  void _play() {
    _playedGeneration = widget.controller.generation;
    _timer?.cancel();
    _hop.stop();
    switch (widget.controller.state) {
      case PetState.idle:
        _show(PixelFrame.idle);
        // The blink cell is derived from the idle drawing itself, so this
        // swap moves nothing but the eyes — safe to run unattended.
        _scheduleBlink();
      case PetState.walk:
        _walkTick = 0;
        _show(PixelChoreography.walkFrameAt(0));
        _timer = Timer.periodic(PixelChoreography.walkFrameInterval, (_) {
          _walkTick++;
          _show(PixelChoreography.walkFrameAt(_walkTick));
        });
      case PetState.jump:
        _show(PixelFrame.jump);
        _hop.forward(from: 0);
      case PetState.wink:
        _show(PixelFrame.wink);
        _timer = Timer(PixelChoreography.winkHold, _finishOneShot);
    }
  }

  void _scheduleBlink() {
    _timer = Timer(PixelChoreography.nextBlinkDelay(_random), () {
      _show(PixelFrame.blink);
      _timer = Timer(PixelChoreography.blinkHold, () {
        _show(PixelFrame.idle);
        _scheduleBlink();
      });
    });
  }

  void _onHopStatus(AnimationStatus status) {
    if (status == AnimationStatus.completed) _finishOneShot();
  }

  void _finishOneShot() {
    final onComplete = widget.onOneShotComplete;
    if (onComplete != null) {
      onComplete();
    } else {
      widget.controller.onOneShotComplete();
    }
  }

  void _show(PixelFrame frame) {
    if (_frame != frame) setState(() => _frame = frame);
  }

  @override
  Widget build(BuildContext context) {
    final frames = _frames;
    if (frames == null) return const SizedBox.shrink();
    return AnimatedBuilder(
      animation: _hop,
      builder: (context, _) => CustomPaint(
        size: Size(48.0 * widget.scale, 64.0 * widget.scale),
        painter: PixelSpritePainter(
          image: frames[_frame]!,
          scale: widget.scale,
          // The hop is a translation of the whole sprite, snapped to whole
          // sprite pixels so the art never lands between its own grid.
          hop: _hop.isAnimating
              ? (math.sin(_hop.value * math.pi) * PixelChoreography.jumpHopPx)
                        .round() *
                    widget.scale.toDouble()
              : 0,
        ),
      ),
    );
  }
}

/// Draws one 48x64 cell at an integer scale with no filtering — the two
/// rules that keep pixel art crisp.
class PixelSpritePainter extends CustomPainter {
  PixelSpritePainter({
    required this.image,
    required this.scale,
    required this.hop,
  });

  final ui.Image image;
  final int scale;

  /// Upward offset in physical pixels, already grid-snapped.
  final double hop;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawImageRect(
      image,
      Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()),
      Rect.fromLTWH(0, -hop, 48.0 * scale, 64.0 * scale),
      Paint()..filterQuality = FilterQuality.none,
    );
  }

  @override
  bool shouldRepaint(PixelSpritePainter old) =>
      old.image != image || old.scale != scale || old.hop != hop;
}
